# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      master:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'your master DB?'
        # Default value if no value is explicitly provided
        default: 'vpcmaster'
        # Input has to be provided for the workflow to run
        required: true
      community:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'your community DB?'
        # Default value if no value is explicitly provided
        default: 'qa-conditions'
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: RunLiquibaseCLICommands
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        uses: actions/checkout@v2
    # Runs a single command using the runners shell
      - name: Send greeting
        run: echo "Hello ${{ github.event.inputs.master }}  ${{ github.event.inputs.community }} "
      
      - name: Test ls  
        run: ls
